name: Release to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Maven Central

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Import GPG private key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > gpg.key
          gpg --batch --import gpg.key
        env:
          GPG_TTY: /dev/tty

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.OSSRH_USERNAME }}</username>
                <password>${{ secrets.OSSRH_PASSWORD }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>gpg</id>
                <properties>
                  <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>
                </properties>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>gpg</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Deploy to Maven Central
        run: mvn clean deploy -B -P gpg
        env:
          GPG_TTY: /dev/tty
